# ______  _   _   _____   _   _   ______  _   _   _   _____   _   _       ___   _____  
#|___  / | | | | /  _  \ | | | | |___  / | | | | | | /  ___| | | | |     /   | /  _  \ 
#   / /  | |_| | | | | | | | | |    / /  | |_| | | | | |     | |_| |    / /| | | | | | 
#  / /   |  _  | | | | | | | | |   / /   |  _  | | | | |     |  _  |   / / | | | | | | 
# / /__  | | | | | |_| | | |_| |  / /__  | | | | | | | |___  | | | |  / /  | | | |_| | 
#/_____| |_| |_| \_____/ \_____/ /_____| |_| |_| |_| \_____| |_| |_| /_/   |_| \_____/ 
#
#ZHICHAO出品必属精品

worlds:
  - world

#是否后台报时
printout: true

#是否同步时间时播报给玩家
remind: true

#如果是整时请写 时:00

#日出时间
raise_time: "7:10"

#日落时间
fall_time: "5:10"
