name: One_day
version: '${project.version}'
main: zzc.one_day.One_day
api-version: 1.19
authors: [ zhouzhichao ]
description: mapping 24000 ticks to 24 hours
website: www.binhaixiaoshu.com

commands:
  one_day:
    description: Setup player's UTC
    usage: /one_day <hour> <minutes>
    actions:
      - '[MESSAGE] test one day command action!'
